DROP TABLE IF EXISTS "Aluno";
CREATE TABLE "Aluno" ("id" INTEGER PRIMARY KEY  NOT NULL , "nome" TEXT, "RG" TEXT, "CPF" TEXT, "data_nascimento" TEXT, "filiacao" TEXT);
INSERT INTO "Aluno" VALUES(1,'José Rodrigues','725138869','98863475118','10/05/2001','Maria Rodrigues');
DROP TABLE IF EXISTS "Curso";
CREATE TABLE "Curso" ("id" INTEGER PRIMARY KEY  NOT NULL , "nome" TEXT, "sigla" TEXT, "nivel" TEXT, "carga_horaria" TEXT, "serie" TEXT, "DOU_Portaria" TEXT);
DROP TABLE IF EXISTS "Disciplina";
CREATE TABLE "Disciplina" ("id" INTEGER PRIMARY KEY  NOT NULL , "nome" TEXT, "sigla_disciplina" TEXT, "carga_horaria" TEXT);
DROP TABLE IF EXISTS "Instituicao";
CREATE TABLE "Instituicao" ("id" INTEGER PRIMARY KEY  NOT NULL , "nome" TEXT, "sigla" TEXT, "endereco" TEXT, "DOU_Portaria" TEXT, "informacoes" TEXT);
DROP TABLE IF EXISTS "Leciona";
CREATE TABLE "Leciona" ("id_professor" INTEGER NOT NULL , "id_disciplina" INTEGER NOT NULL );
DROP TABLE IF EXISTS "Matricula";
CREATE TABLE "Matricula" ("id_aluno" INTEGER NOT NULL , "id_disciplina" INTEGER NOT NULL , "cod_matricula" INTEGER NOT NULL , "data_matricula" TEXT NOT NULL , "data_saida" TEXT NOT NULL , "situacao" BOOL NOT NULL );
DROP TABLE IF EXISTS "Ocorre_Aula";
CREATE TABLE "Ocorre_Aula" ("id_aluno" INTEGER NOT NULL , "id_leciona" INTEGER NOT NULL , "data_hora" TEXT NOT NULL , "presenca" BOOL NOT NULL );
DROP TABLE IF EXISTS "Possui_Curso";
CREATE TABLE "Possui_Curso" ("id_instituicao" INTEGER NOT NULL , "id_curso" INTEGER NOT NULL , "data_criacao" TEXT NOT NULL , "atividade" TEXT NOT NULL );
DROP TABLE IF EXISTS "Possui_Disciplina";
CREATE TABLE "Possui_Disciplina" ("id_turma" INTEGER NOT NULL , "id_disciplina" INTEGER NOT NULL , "sala_local" TEXT NOT NULL );
DROP TABLE IF EXISTS "Possui_Turma";
CREATE TABLE "Possui_Turma" ("id_curso" INTEGER NOT NULL , "id_turma" INTEGER NOT NULL , "data_criacao" TEXT NOT NULL , "atividade" TEXT NOT NULL );
DROP TABLE IF EXISTS "Professor";
CREATE TABLE "Professor" ("id" INTEGER PRIMARY KEY  NOT NULL , "nome" TEXT, "CPF" TEXT, "RG" TEXT, "data_nascimento" TEXT, "formacao" TEXT);
DROP TABLE IF EXISTS "Turma";
CREATE TABLE "Turma" ("id" INTEGER PRIMARY KEY  NOT NULL , "sigla_turma" TEXT);
CREATE UNIQUE INDEX "Alunos" ON "Aluno" ("id" ASC, "nome" ASC, "RG" ASC, "CPF" ASC, "data_nascimento" ASC, "filiacao" ASC);
CREATE UNIQUE INDEX "Cursos" ON "Curso" ("id" ASC, "nome" ASC, "sigla" ASC, "nivel" ASC, "carga_horaria" ASC, "serie" ASC, "DOU_Portaria" ASC);
CREATE UNIQUE INDEX "Disciplinas" ON "Disciplina" ("id" ASC, "nome" ASC, "sigla_disciplina" ASC, "carga_horaria" ASC);
CREATE UNIQUE INDEX "Instituicoes" ON "Instituicao" ("id" ASC, "nome" ASC, "sigla" ASC, "endereco" ASC, "DOU_Portaria" ASC, "informacoes" ASC);
CREATE UNIQUE INDEX "Professores" ON "Professor" ("id" ASC, "nome" ASC, "CPF" ASC, "RG" ASC, "data_nascimento" ASC, "formacao" ASC);
CREATE UNIQUE INDEX "Turmas" ON "Turma" ("id" ASC, "sigla_turma" ASC);
